name: train-my-model

on: [push]
  paths:
    - '!cml.yml'  # Exclude the tests.yml file

jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - name: Train model
        run: |
          pip install -r requirements.txt  # install dependencies
          python cookie/train_cml.py  # run training
      - name: Write report
        env:
          # this authenticates that the right permissions are in place
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat classification_report.txt >> report.md
          cml comment create report.md
          cml send-comment report.md
