name: "Code Check"

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  codecheck:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    # Cache Python dependencies
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_tests.txt

    - name: Install Ruff
      run: |
        pip install ruff

    - name: Run Ruff Check and Format
      run: |
        ruff check .
        ruff format .

    - name: Install Mypy
      run: |
        pip install mypy

    - name: Run Mypy
      run: |
        mypy .
