name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      token: ${{ secrets.DOCKER_HUB_TOKEN }}
      username: ${{ secrets.DOCKER_HUB_USERNAME }}
      repository: ${{ secrets.DOCKER_HUB_REPOSITORY }}
      password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: $username
          password: $password
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: continuous:latest
          file: dockerfiles/continuous.dockerfile
